# Generated by Django 3.2.12 on 2024-02-17 18:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='messages',
        ),
    ]
