# Generated by Django 3.2.12 on 2024-02-17 18:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0003_auto_20240217_1845'),
    ]

    operations = [
        migrations.RenameField(
            model_name='chathistory',
            old_name='message',
            new_name='category',
        ),
    ]
