# Generated by Django 3.2.12 on 2024-02-17 18:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('category', '0004_rename_message_chathistory_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chathistory',
            name='category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='category.category'),
            preserve_default=False,
        ),
    ]
